/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author mvene
 */
public class ventanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form ventanaInicio
     */
    public ventanaInicio() {
        initComponents();
    }
    
    public String tipoVentanaVerde;
    public String tipoVentanaAmarillo;
    public int contadorVentanasVerdes=0;
    public int contadorVentanasAmarillas=0;

    public String getTipoVentanaVerde() {
        return tipoVentanaVerde;
    }

    public void setTipoVentanaVerde(String tipoVentanaVerde) {
        this.tipoVentanaVerde = tipoVentanaVerde;
    }

    public String getTipoVentanaAmarillo() {
        return tipoVentanaAmarillo;
    }

    public void setTipoVentanaAmarillo(String tipoVentanaAmarillo) {
        this.tipoVentanaAmarillo = tipoVentanaAmarillo;
    }

    public int getContadorVentanasVerdes() {
        return contadorVentanasVerdes;
    }

    public void setContadorVentanasVerdes(int contadorVentanasVerdes) {
        this.contadorVentanasVerdes = contadorVentanasVerdes;
    }

    public int getContadorVentanasAmarillas() {
        return contadorVentanasAmarillas;
    }

    public void setContadorVentanasAmarillas(int contadorVentanasAmarillas) {
        this.contadorVentanasAmarillas = contadorVentanasAmarillas;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ButtonHeap = new javax.swing.JButton();
        ButtonColaP = new javax.swing.JButton();
        ButtonLetsGo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ButtonHeap1 = new javax.swing.JButton();
        ButtonColaP1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextVentanaVerde = new javax.swing.JTextField();
        jTextVentanaAmarilla = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextMinimo = new javax.swing.JTextField();
        jTextMaximo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 36)); // NOI18N
        jLabel1.setText("EmergencyTEC");

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        jLabel2.setText("Seleccione el tipo de estructura prioritaria a utilizar");

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        jLabel3.setText("Bienvenido a");

        ButtonHeap.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        ButtonHeap.setText("Heaps");
        ButtonHeap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHeapActionPerformed(evt);
            }
        });

        ButtonColaP.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        ButtonColaP.setText("Cola Prioritaria");
        ButtonColaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonColaPActionPerformed(evt);
            }
        });

        ButtonLetsGo.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 24)); // NOI18N
        ButtonLetsGo.setText("Ir al Sistema");
        ButtonLetsGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLetsGoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        jLabel4.setText("Seleccione el tipo de estructura prioritaria a utilizar");

        ButtonHeap1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        ButtonHeap1.setText("Heaps");
        ButtonHeap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHeap1ActionPerformed(evt);
            }
        });

        ButtonColaP1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        ButtonColaP1.setText("Cola Prioritaria");
        ButtonColaP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonColaP1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        jLabel5.setText("Ventanillas Verdes");

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        jLabel6.setText("Ventanillas Amarillas");

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        jLabel7.setText("Cantidad de ventanillas");

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        jLabel8.setText("Cantidad de ventanillas");

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        jLabel9.setText("Tiempo mínimo");

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        jLabel10.setText("Tiempo máximo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(ButtonLetsGo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextVentanaVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextVentanaAmarilla, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(jTextMinimo)
                            .addComponent(jTextMaximo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(ButtonHeap1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(ButtonColaP1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(ButtonHeap, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(ButtonColaP, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel6)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonColaP)
                    .addComponent(ButtonHeap))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextVentanaVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonHeap1)
                    .addComponent(ButtonColaP1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextVentanaAmarilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(ButtonLetsGo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonLetsGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLetsGoActionPerformed
        contadorVentanasVerdes= Integer.parseInt(jTextVentanaVerde.getText());
        contadorVentanasAmarillas= Integer.parseInt(jTextVentanaAmarilla.getText());
        interfaz dt = new interfaz(tipoVentanaAmarillo,tipoVentanaVerde,contadorVentanasVerdes,contadorVentanasAmarillas,jTextMinimo.getText(),jTextMaximo.getText());
        dt.setVisible(true);
        dt.setTitle("Control de entregas");
    }//GEN-LAST:event_ButtonLetsGoActionPerformed

    private void ButtonHeapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHeapActionPerformed
        tipoVentanaVerde = "heap";
    }//GEN-LAST:event_ButtonHeapActionPerformed

    private void ButtonColaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonColaPActionPerformed
        tipoVentanaVerde = "cola";
    }//GEN-LAST:event_ButtonColaPActionPerformed

    private void ButtonHeap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHeap1ActionPerformed
        tipoVentanaAmarillo ="heap";
    }//GEN-LAST:event_ButtonHeap1ActionPerformed

    private void ButtonColaP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonColaP1ActionPerformed
        tipoVentanaAmarillo = "cola";
    }//GEN-LAST:event_ButtonColaP1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonColaP;
    private javax.swing.JButton ButtonColaP1;
    private javax.swing.JButton ButtonHeap;
    private javax.swing.JButton ButtonHeap1;
    private javax.swing.JButton ButtonLetsGo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextMaximo;
    private javax.swing.JTextField jTextMinimo;
    private javax.swing.JTextField jTextVentanaAmarilla;
    private javax.swing.JTextField jTextVentanaVerde;
    // End of variables declaration//GEN-END:variables
}
